import Script from "next/script";
import { Alumni_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import VerticalSeparator from "@/components/Separator/VerticalSeparator";
import Socials from "@/components/Socials";
import Footer from "@/components/Footer";

const alumniSans = Alumni_Sans({
  subsets: ["latin"],
  variable: "--font-family",
});

export const metadata = {
  title: "CSC Heilbronn - Cannabis Social Club im Großraum Heilbronn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={alumniSans.className}>
        <Navigation />

        <div id="page-wrap">
          {children}

          <VerticalSeparator size="32px" />
          <Socials />

          <VerticalSeparator size="32px" />
          <Footer />
        </div>

        {/* <!-- Global site tag (gtag.js) - Google Analytics --> */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-GV1MVJLQV5"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-GV1MVJLQV5');
        `}
        </Script>
      </body>
    </html>
  );
}
