import Navigation from '@/components/Navigation'
import './globals.css'
import { Alumni_Sans } from 'next/font/google'
import Footer from '@/components/Footer'
import VerticalSeparator from '@/components/Separator/VerticalSeparator'
import Socials from '@/components/Socials'

const alumniSans = Alumni_Sans({
  subsets: ['latin'],
  variable: '--font-family',
})

export const metadata = {
  title: 'CSC Heilbronn - Cannabis Social Club im Großraum Heilbronn',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={alumniSans.className}>
        <Navigation />

        <div id="page-wrap">
          {children}

          <VerticalSeparator size='32px' />
          <Socials />

          <VerticalSeparator size='32px' />
          <Footer />
        </div>
      </body>
    </html>
  )
}
